change want/have to only negotiate one module/capability at once
vt6/vt6 pull request #27
Opened 2018-07-15 19:57 UTC by majewsky

This vastly simplifies implementations. The previous format looks nice on paper, but requires an absurd amount of bookkeeping on the server side.

2018-07-22 18:21 UTC, laerling requested changes

2018-07-22 18:21 UTC, laerling commented on spec/core/1.0.md
> +If the `want` message requests usage of a module and the server agrees to using that module, it MUST reply with a `have` message with three arguments: the module name, the major and minor version of
Why not `full-version`?

2018-07-22 18:21 UTC, laerling commented on spec/core/1.0.md
> +If the `want` message is valid, but the server does not agree to the requested module and capability, it MUST reply with a `have` message with zero arguments.
s/and/or/

2018-07-22 18:21 UTC, laerling commented on spec/core/1.0.md
> +If the `want` message requests usage of a capability and the server agrees to using that module, it MUST reply with a `have` message with a single argument: the capability name as accepted by `<scope
s/module/capability/

2018-07-22 18:21 UTC, hkgit03 commented on spec/core/1.0.md
> +Receipt of this `have` message entitles the client to use all message types, properties and behavior defined in a specification of that module with the same major version number and the same, or a sm
Why should the client be entitled to use everything of a module or anything from the module in the first place? Also, the second half sentence concerns capabilities, while the first one concerns modules. Split that into two sentences.

2018-07-22 18:21 UTC, hkgit03 commented on spec/core/1.0.md
> +When a `want` message concerns the same capability as an earlier `want` message, the server MUST reply consistently.
Duplicate of line 405, although this time with explanation (line 415).

2018-07-22 18:21 UTC, hkgit03 commented on spec/core/1.0.md
> +When a `want` message concerns the same module as an earlier `want` message, the server MUST reply consistently.
Duplicate of line 414.

2018-07-22 18:24 UTC, majewsky commented on spec/core/1.0.md
> +If the `want` message requests usage of a capability and the server agrees to using that module, it MUST reply with a `have` message with a single argument: the capability name as accepted by `<scope
No, 405 is about modules. 414 is about capabilities.

2018-07-22 18:25 UTC, majewsky commented on spec/core/1.0.md
> +Receipt of this `have` message entitles the client to use all message types, properties and behavior defined in a specification of that module with the same major version number and the same, or a sm
No, you're misunderstanding this convoluted sentence. This paragraph is only about negotiating capabilities.

2018-07-22 18:25 UTC, majewsky commented on spec/core/1.0.md
> +When a `want` message concerns the same capability as an earlier `want` message, the server MUST reply consistently.
No. See above.

2018-07-22 18:25 UTC, majewsky commented on spec/core/1.0.md
> +When a `want` message concerns the same module as an earlier `want` message, the server MUST reply consistently.
No. See above.

2018-07-23 09:26 UTC, laerling commented on spec/core/1.0.md
> +If the `want` message requests usage of a capability and the server agrees to using that module, it MUST reply with a `have` message with a single argument: the capability name as accepted by `<scope
Then better write "the module that defines that capability", or something like that.

2018-07-23 21:32 UTC, hkgit03 commented
>Riot, pls.

2018-07-25 22:43 UTC, laerling approved these changes

2018-07-26 09:34 UTC, merged